name: Deploy Laravel App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar PHP, Composer, Node
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, openssl, pdo, tokenizer
          tools: composer

      - name: Ir para o diretório do projeto
        run: cd ProjetoTCC

      - name: Instalar dependências PHP
        run: |
          cd ProjetoTCC
          composer install --no-dev --optimize-autoloader

      - name: Instalar dependências JS e compilar assets
        run: |
          cd ProjetoTCC
          npm install
          npm run build

      - name: Configurar variáveis .env
        run: |
          cd ProjetoTCC
          cp .env.example .env
          php artisan key:generate

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
<<<<<<< HEAD
          app-name: Verdecalc
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ProjetoTCC
=======
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0361C436E2904DF5A6CDAA846FAAD4D8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_849C5DE1631249A29B323448AF822C42 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5BC2A5632B5C43C9BFDCC72027BDD3E5 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'verdecalc'
          slot-name: 'Production'
          package: .
          
>>>>>>> 882bf2d0271736f8817d28d72c9b86bc1fe0aec0
